# Generated by Django 2.2.16 on 2021-10-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_follow"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                fields=("user", "author"), name="unique follow"
            ),
        ),
    ]
